# Generated by Django 5.2.5 on 2025-08-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_nickname', models.CharField(default='', max_length=150, primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(default='', max_length=150)),
                ('user_email', models.CharField(max_length=128)),
                ('user_age', models.IntegerField(default=0)),
                ('user_password', models.CharField(default='', max_length=128)),
                ('user_cpf', models.CharField(default='', max_length=11)),
                ('user_phone', models.CharField(default='', max_length=15)),
                ('user_city', models.CharField(default='', max_length=128)),
                ('user_birthdate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
