# Generated by Django 5.2.5 on 2025-08-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_remove_user_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_cpf',
            field=models.CharField(default='', max_length=20),
        ),
    ]
